# Generated by Django 6.0.2 on 2026-02-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='absents',
            field=models.ManyToManyField(blank=True, related_name='absent_sessions', to='attendance.student'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
